name: Project

on:
  workflow_dispatch:

jobs:
  start-application:
    name: Start application
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          
      - name: Install dependencies
        run: npm ci || npm install
        
      - name: Deploy Preview with Localtonet
        uses: actions-hub/localtonet@main
        with:
          port: 5000
          token: ${{ secrets.LOCALTONET_TOKEN }}
          
      - name: Start application
        run: node server.js
